### ISSUE TITLE
NOT WORKING!!

### ISSUE THREAD

**Issue by folke** [dundargoc/fakedonalds.nvim#1]
I INSTALLED THE COLORSCHEME AND IT DOESNT WORK!! FIX IT YESTERDAY!!!!

**Comment by dundargoc** [comment]
This is currently blocked by two things:

- I don't know how to create plugins
- I don't know how to create colorschemes

Once I learn these I will be able to finish this plugin. Thank you for your patience.

**Comment by dundargoc** [comment]
OK, so I have a prototype colorscheme ready now. Please test it.

**Comment by folke** [comment]
Love it! :)
